import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import LenisScroll from "@/components/LenisScroll";
const poppins = Poppins({
    subsets: ["latin"],
    weight: ["400", "500", "600", "700"],
    variable: "--font-poppins",
});
export const metadata: Metadata = {
  title: "Thumbly",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className = {`${poppins}`}
    >
      <head>
      <link rel="preload" href="/assets/background-splash.svg" as="image" />
      </head>
      <body>
        <LenisScroll/>
        <Navbar/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
